color: null
description: null
fieldLayouts:
  bffe9425-e1bd-48cc-9941-d3f8ab592a47:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        name: Content
        uid: 43e46f54-132d-4e0e-8c75-6a29c04a2e2a
        userCondition: null
handle: announcements
hasTitleField: false
icon: megaphone
name: Announcements
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
