color: null
description: null
fieldLayouts:
  356d36e4-2685-4340-8b21-353308e021e8:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-12-10T00:44:31+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 994238ed-79d7-4fdd-b9a1-314968ea04ad
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-10T00:45:43+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cfdb4cfd-3dce-4d62-b0eb-ff0cca5014df # Blog Blocks
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9d69bd1c-a695-4849-bb70-bf10cb81bab6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: fa03bbef-7ab3-482a-beee-4cfa1fc4d0a3
        userCondition: null
handle: blogpage
hasTitleField: true
icon: null
name: BlogPage
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
