color: null
description: null
fieldLayouts:
  356d36e4-2685-4340-8b21-353308e021e8:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-12-10T00:44:31+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 994238ed-79d7-4fdd-b9a1-314968ea04ad
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-28T18:09:10+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 51d4c03c-2317-443b-860f-1fbd1232e534 # Description
            handle: null
            includeInCards: false
            instructions: 'The introductory description for your blog post that will appear on the cards linking to the blog entry itself. '
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 980c8587-f0cc-4b88-b880-f2efbecd2b46
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-28T17:38:32+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 42a50e3b-7d07-410d-a585-dec58552a102 # Preview Image
            handle: null
            includeInCards: false
            instructions: 'The preview image for your blog post that will appear on the cards linking to the blog entry itself.'
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 87785f2f-b7b5-4600-8905-9b432716269c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-28T17:38:32+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 31fe2c30-be09-4ce5-af27-39cdfec7f12d # Scrolling Image
            handle: null
            includeInCards: false
            instructions: 'If you wish for an image to follow readers as they scroll through your blog entry on desktop, please select one below'
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f93775a9-a9d9-45a7-94ac-f4effb799c17
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-10T00:45:43+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cfdb4cfd-3dce-4d62-b0eb-ff0cca5014df # Blog Blocks
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9d69bd1c-a695-4849-bb70-bf10cb81bab6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: fa03bbef-7ab3-482a-beee-4cfa1fc4d0a3
        userCondition: null
handle: blogpage
hasTitleField: true
icon: memo
name: BlogPage
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
