color: null
description: null
fieldLayouts:
  cf06fc67-001d-4d1e-b942-eff57fc13062:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        name: Content
        uid: 54909f67-afa9-47c9-a246-7e3abd2f53fd
        userCondition: null
handle: footer
hasTitleField: false
icon: rectangle-wide
name: 'Site Footer'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
