color: null
description: null
fieldLayouts:
  b9afa303-580e-4488-8e51-4e1cade9dc79:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-12-26T16:48:45+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8643638c-be2b-4c9a-8fc0-0091e360deb7 # Paragraph Text
            handle: null
            includeInCards: false
            instructions: null
            label: 'Introduction Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ddc3d302-72a0-473a-aa6e-002bae8e743f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: aafca617-419f-4890-8088-83ed1b38c8eb
        userCondition: null
handle: intro
hasTitleField: false
icon: hand-wave
name: Introduction
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
