color: null
description: null
fieldLayouts:
  5c9df4ab-9cc8-4d4a-9581-9a5f205a31f2:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-12-26T16:39:46+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a06cf119-1a9b-45ce-b0fd-86eeb6b1ee57 # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 34de3606-a4b9-4975-8e53-4df77335cfb9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-26T16:39:46+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 14d9aa12-2674-4406-bb17-8474714159c7 # Subheading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c14d7e08-f55b-498e-b6cb-403a89fe807e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6ab4266b-aca8-4e94-bc2c-852898478f5a
        userCondition: null
handle: marqueeWide
hasTitleField: false
icon: display
name: 'Marquee Wide'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
