color: null
description: null
fieldLayouts:
  f431b35f-26af-4c5b-9a53-ae81edd9f95f:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-01-22T01:05:35+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ed8ea969-93fd-40e4-a6eb-0823c41e2c93 # 1st Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 125573f9-89ac-4f4f-ba4f-2dad5ef42613
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-22T01:06:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a06cf119-1a9b-45ce-b0fd-86eeb6b1ee57 # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3e74feca-bf67-4b90-b460-b33f38e74ea8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-22T01:06:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 14d9aa12-2674-4406-bb17-8474714159c7 # Subheading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bc0415d0-fd24-458b-9599-479a0266c0bb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8a4cf0ed-48a6-4a74-98d0-abd36725c435
        userCondition: null
handle: marqueeImage
hasTitleField: false
icon: panorama
name: 'Marquee (Image)'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
