color: null
description: null
fieldLayouts:
  ed26ddf9-ad31-498c-9464-85124f573227:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        name: Content
        uid: 578fa02d-ec4c-41c8-9c35-d7068b212333
        userCondition: null
handle: masterHero
hasTitleField: false
icon: mask
name: 'Large Hero'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
