color: null
description: null
fieldLayouts:
  92acdb65-53d8-45a9-8bcb-d4328d4cd86f:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        name: Content
        uid: b15aa583-1277-4de8-bf06-8ebf18c6494d
        userCondition: null
handle: miniMarquee
hasTitleField: false
icon: gallery-thumbnails
name: 'Mini Marquee'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
