color: null
description: null
fieldLayouts:
  ee75400f-9013-4960-ba92-f5718f73ba06:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        name: Content
        uid: 139ace05-4adc-49e5-923e-e0ee76dd8855
        userCondition: null
handle: navigation
hasTitleField: false
icon: bars
name: Navigation
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
