color: null
description: null
fieldLayouts:
  c866adc0-9581-4cd1-9a73-06e6e260a18e:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        name: Content
        uid: a185920d-3f48-4d30-b4dc-d3b1cea68420
        userCondition: null
handle: navigationHero
hasTitleField: false
icon: map-location-dot
name: 'Navigation With Hero'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
