color: null
description: null
fieldLayouts:
  6b552744-62cd-462d-ac95-3375713ae83c:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        name: Content
        uid: 04e4322b-b53c-48e6-ba10-e9c19858f362
        userCondition: null
handle: paragraphAlt
hasTitleField: false
icon: align-justify
name: Paragraph
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
