color: null
description: null
fieldLayouts:
  2fa0d3d2-d0c2-403f-8c4c-f8887a6177ef:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-01-23T03:38:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d26b5ae7-14f1-4158-a982-94713d28f1c1 # Collapse Mobile
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 97efbab1-a2ec-4d07-b07b-73ffd988ee5b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1202c056-d5c4-4c3d-8bca-73d9575cd406
        userCondition: null
handle: spaceSM
hasTitleField: false
icon: angles-up-down
name: 'Small Spacer'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
