color: null
description: null
fieldLayouts:
  d0b49bea-7bc2-42ac-b727-fc48c1169125:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        name: Content
        uid: 3d391cc9-933b-49df-a27b-cb123f738fe0
        userCondition: null
handle: spaceMD
hasTitleField: false
icon: angles-up-down
name: 'Medium Spacer'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
