columnSuffix: null
handle: blogBlocks
instructions: null
name: 'Blog Blocks'
searchable: false
settings:
  createButtonLabel: 'Add Elements'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 901cd1f4-fb95-4966-ace2-220aa081d9d8 # Paragraph
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 52684aa2-3417-4e68-9206-d6371412031b # Quote
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - e04778ba-b214-41ff-89f1-d5be2d84be91 # Image
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - cdb1f79d-3f27-4e7f-a8ca-be2236133ea7 # Introduction
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - a4781ff6-b41f-478f-a860-fc78b905f8e8 # Headline
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 5e485214-bcce-49c6-8af4-0f5e89158d43 # Marquee
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - ec5addeb-6b15-4f51-8053-6cb8a33a63a7 # Signature
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 8aee16ba-55f9-4669-9657-c5cfe6a5d3d3 # Follow Image
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: true
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
