columnSuffix: null
handle: blogBlocks
instructions: null
name: 'Blog Blocks'
searchable: false
settings:
  createButtonLabel: 'Add Elements'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 901cd1f4-fb95-4966-ace2-220aa081d9d8 # Paragraph
        -
          - description
          - 'A standard editorial style paragraph. Recommended character length of approximately 500 characters per paragraph. '
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 52684aa2-3417-4e68-9206-d6371412031b # Quote
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - e04778ba-b214-41ff-89f1-d5be2d84be91 # Image
        -
          - description
          - 'An image that will appear within the body of your blog article. '
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - cdb1f79d-3f27-4e7f-a8ca-be2236133ea7 # Introduction
        -
          - description
          - 'An introduction that explains what your blog entry is about'
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - a4781ff6-b41f-478f-a860-fc78b905f8e8 # Headline
        -
          - description
          - 'The title of your blog entry'
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 5e485214-bcce-49c6-8af4-0f5e89158d43 # Marquee
        -
          - description
          - 'The "color splash" marquee for your blog entry. Please note that you should add the "color palette" block and select colors if you wish to customize them. '
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - ec5addeb-6b15-4f51-8053-6cb8a33a63a7 # Signature
        -
          - description
          - "Jessica's Signature"
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - f2351a3c-f486-456e-9833-72f1f821b2c6 # Color Palette
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: true
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
