columnSuffix: null
handle: colorSelection
instructions: null
name: 'Color Selection'
searchable: false
settings:
  allowCustomColors: true
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
