columnSuffix: null
handle: pageBlocks
instructions: null
name: 'Page Blocks'
searchable: false
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 3158c64d-4653-44d7-8ef9-18f805862e13 # exampleModule
        -
          - name
          - 'Example Module'
        -
          - handle
          - exampleModule
        -
          - description
          - 'An example of how a module is built in Filament Boilerplate'
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 0b791488-8988-45c1-b86f-3bd2a9d0f36e # Large Spacer
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - f5d67f5c-dd8e-4565-a1bc-e0aed82e9f75 # Medium Spacer
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 1e0e84fb-9ba3-41ec-87d0-22472b8c1ae9 # Small Spacer
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - b49dcac4-4dca-4e71-9925-c677816d034c # Aside Paragraph
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 840e4b3e-cde9-4478-8400-f2e9f30c147c # Editorial Collage
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - b5253cdf-98b0-4938-9366-0b2d4914edb3 # Billboard Split
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 0ca218cb-9082-405d-93a1-5f3fe4324099 # Editorial Columns
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 0372f3ed-21a0-4fba-b318-c137111d8d27 # Pattern Spacer
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 9655ee03-f1c7-4a52-b72b-f82b1e908aa7 # Cinema Slider
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - addc69ef-1366-47cc-b9aa-477cbdd76685 # Large Hero
        -
          - name
          - 'Grand Marquee'
        -
          - handle
          - grandMarquee
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 5bd0a3b2-88ff-464d-8c51-ae2aea23b8d1 # Navigation
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 8fde69fc-adc8-470f-ace8-add4c0a4de74 # Announcements
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 4446a9d7-df5f-441f-8d02-6cf3df460582 # Navigation With Hero
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - ea82e941-3e2c-4cd7-bcbb-70ce15e46ac7 # Mini Marquee
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 7eb60045-099b-4bfe-ac3a-d4d44ba037a1 # Site Footer
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
