dateModified: 1769051236
email:
  fromEmail: creative@raraavis.design
  fromName: Filament-Boilerplate
  replyToEmail: null
  template: null
  transportSettings:
    command: '/usr/local/bin/mailpit sendmail -t --smtp-addr 127.0.0.1:1025'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  pouredOutAssets:
    hasUrls: true
    name: 'Poured Out Assets'
    settings:
      cdnUrlPattern: ''
      customSubfolder: ''
      makeUploadsPublic: true
      optimisePrefix: ''
      optimiseUrlPattern: ''
      projectSlug: ''
      securityKey: ''
      subfolder: local/
    type: servd\AssetStorage\AssetsPlatform\Fs
    url: 'https://keen-barbet.files.svdcdn.com'
meta:
  __names__:
    0b791488-8988-45c1-b86f-3bd2a9d0f36e: 'Large Spacer' # Large Spacer
    0ca218cb-9082-405d-93a1-5f3fe4324099: 'Editorial Columns' # Editorial Columns
    1e0e84fb-9ba3-41ec-87d0-22472b8c1ae9: 'Small Spacer' # Small Spacer
    1fd40fbd-1d28-4736-b094-9cbfd1fd7b8c: 'Announcement Text' # Announcement Text
    02bb2a8f-74c7-4c41-9cff-783b9f3eba9d: Author # Author
    2db1f353-5cc8-40db-b2de-583a39d92a64: 'Public Schema' # Public Schema
    3a4d3adf-4ddc-4282-ac31-343b314828c4: 'Third Paragraph' # Third Paragraph
    3e34b7dc-42a3-4865-9e9c-001b4eb654af: "Author's Title" # Author's Title
    4b62f1ab-cb3e-490e-ad54-2a72dc774c37: Blogs # Blogs
    5bd0a3b2-88ff-464d-8c51-ae2aea23b8d1: Navigation # Navigation
    5e485214-bcce-49c6-8af4-0f5e89158d43: Marquee # Marquee
    6c095355-9e0e-475d-aaf6-87d60039e126: 'Marquee (Image)' # Marquee (Image)
    7a3cf3e9-179e-4cbe-bc17-1857335d6fa5: '2nd Image' # 2nd Image
    7b88d50b-5f6f-4cf7-9f9d-4c8a40da91c9: 'Marquee Wide' # Marquee Wide
    7eb60045-099b-4bfe-ac3a-d4d44ba037a1: 'Site Footer' # Site Footer
    8fde69fc-adc8-470f-ace8-add4c0a4de74: Announcements # Announcements
    8ffacfc9-b77c-4ffb-bb3e-e31f8b956799: Images # Images
    9c674c15-6e9e-481d-bfbe-8945a1804194: 'First Paragraph' # First Paragraph
    9cf0cdc6-4797-4922-937d-abaa90c55f4e: Paragraph # Paragraph
    14d9aa12-2674-4406-bb17-8474714159c7: Subheading # Subheading
    15ae5794-eb4a-4a75-b271-9d44b8612a74: '5th Image' # 5th Image
    31fe2c30-be09-4ce5-af27-39cdfec7f12d: 'Scrolling Image' # Scrolling Image
    39cf4a9d-2ccb-42bd-a569-80dc50265ff3: Gallery # Gallery
    42a50e3b-7d07-410d-a585-dec58552a102: 'Preview Image' # Preview Image
    48eabee0-5886-430a-ac24-e708a30e425a: Filament-Boilerplate # Filament-Boilerplate
    51d4c03c-2317-443b-860f-1fbd1232e534: Description # Description
    72cc4092-dce2-4057-a061-5bf104dd7d96: Filament-Boilerplate # Filament-Boilerplate
    77eca617-e8ed-4e88-b7fb-12bb67300759: 'Second Paragraph' # Second Paragraph
    79a04cd8-507b-46a3-ae00-a598890ab36b: 'Color Palette' # Color Palette
    161e35c5-199b-4d9c-b090-9dc1c61bc616: Default # Default
    0372f3ed-21a0-4fba-b318-c137111d8d27: 'Pattern Spacer' # Pattern Spacer
    390f7f35-3009-4309-928e-7b56098ddcd3: BlogPage # BlogPage
    450c53ab-10ae-471a-9a25-403cb7b992ff: 'Color Background' # Color Background
    768f6b29-6796-4341-baed-ce919fde46a6: Shop # Shop
    840e4b3e-cde9-4478-8400-f2e9f30c147c: 'Editorial Collage' # Editorial Collage
    869b188c-653d-449b-8c3d-cf1513293f4f: 'Column List' # Column List
    901cd1f4-fb95-4966-ace2-220aa081d9d8: Paragraph # Paragraph
    975b8327-89b8-42ca-b5aa-e291d9f9677c: '3rd Image' # 3rd Image
    04303a81-f680-4edf-81d3-bd9d119c7390: 'Color Selection' # Color Selection
    4446a9d7-df5f-441f-8d02-6cf3df460582: 'Navigation With Hero' # Navigation With Hero
    7391a08d-de21-4203-95e1-632a98a99d23: 'Global Content' # Global Content
    9655ee03-f1c7-4a52-b72b-f82b1e908aa7: 'Cinema Slider' # Cinema Slider
    20208dd2-1f00-4c17-911c-5bf21613181f: Marquee # Marquee
    52684aa2-3417-4e68-9206-d6371412031b: Quote # Quote
    144593fe-da30-41d5-8ec8-b757273bb41b: Announcement # Announcement
    271526fc-7b30-4ed4-8641-c83754a371c7: Closing # Closing
    289828ba-e105-446f-8deb-d5509101d02b: Image # Image
    6054654d-f5d7-4df9-bae9-4da624aa2bbe: 'Three Cards' # Three Cards
    8643638c-be2b-4c9a-8fc0-0091e360deb7: 'Paragraph Text' # Paragraph Text
    43351229-39dc-4070-b365-29e094fb7db0: Quote # Quote
    a06cf119-1a9b-45ce-b0fd-86eeb6b1ee57: Heading # Heading
    a95a6756-5f44-4880-9bf7-17b12bf0b1e7: Colors # Colors
    a4781ff6-b41f-478f-a860-fc78b905f8e8: Headline # Headline
    aa15edf9-5fc0-40cc-8eb1-570557b0c72f: StandardPage # StandardPage
    ab2a1412-8d01-4b29-a57d-80a0f008efab: Pages # Pages
    addc69ef-1366-47cc-b9aa-477cbdd76685: 'Large Hero' # Large Hero
    affe6a11-2e34-40ec-a742-3766960fdfd3: Gallery # Gallery
    b0425f19-189b-432e-a981-4fccc8ecd8f9: Quote # Quote
    b0514dd3-fb9c-4848-95ed-318cea87b2b5: Blogs # Blogs
    b49dcac4-4dca-4e71-9925-c677816d034c: 'Aside Paragraph' # Aside Paragraph
    b5253cdf-98b0-4938-9366-0b2d4914edb3: 'Billboard Split' # Billboard Split
    bffade2e-a26c-4f6d-b1f3-ba11be0c25c6: Simple # Simple
    c3b1d63c-af69-45ad-ae0c-9b47a6c0c027: Headline # Headline
    c815f331-a25c-4bd6-8393-2dcac79cd71e: "Author's Name" # Author's Name
    ca591ad2-56c3-4369-aa63-797cddbea65e: Assets # Assets
    cac287ab-f575-4bdf-9836-b06446a54504: 'Grand Marquee' # Grand Marquee
    cdb1f79d-3f27-4e7f-a8ca-be2236133ea7: Introduction # Introduction
    cdf8dc00-7c81-40b8-a30f-d30c796267b8: color # color
    cf1c951a-5742-4fec-8a93-cac307d4f30b: 'Page Blocks' # Page Blocks
    cfdb4cfd-3dce-4d62-b0eb-ff0cca5014df: 'Blog Blocks' # Blog Blocks
    daaf0a23-3781-475b-9c1d-145b15108605: '4th Image' # 4th Image
    e04778ba-b214-41ff-89f1-d5be2d84be91: Image # Image
    ea82e941-3e2c-4cd7-bcbb-70ce15e46ac7: 'Mini Marquee' # Mini Marquee
    ec5addeb-6b15-4f51-8053-6cb8a33a63a7: Signature # Signature
    ed8ea969-93fd-40e4-a6eb-0823c41e2c93: '1st Image' # 1st Image
    f5d67f5c-dd8e-4565-a1bc-e0aed82e9f75: 'Medium Spacer' # Medium Spacer
    f2351a3c-f486-456e-9833-72f1f821b2c6: 'Color Palette' # Color Palette
    ffa62b38-7996-4d0e-9542-8dfcce600f43: About # About
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  cp-css:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
    settings:
      additionalCss: "/* Sidebar background color */\r\n\r\n@import url('https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap');\r\n\r\nbody {\r\n  font-family: 'Montserrat', sans-serif;\r\n}\r\n\r\nbody.login main {\r\n  position: relative;\r\n  z-index: 0;\r\n  overflow: \r\n  hidden;\r\n}\r\n\r\n.cp-icon {\r\n    color:#755cef;\r\n}\r\n\r\n/* Blurred background image */\r\nbody.login main::before {\r\n  content: \"\";\r\n  position: absolute;\r\n  inset: 0;\r\n  background-image: url(\"https://images.pexels.com/photos/114820/pexels-photo-114820.jpeg?_gl=1*c292t5*_ga*ODQyNTExMDguMTc1MjQyODQyMg..*_ga_8JE65Q40S6*czE3NTI0Mjg0MjIkbzEkZzEkdDE3NTI0MjkxNjMkajQ2JGwwJGgw\");\r\n  background-size: cover;\r\n  background-position: center;\r\n  filter: blur(8px);\r\n  z-index: -2;\r\n}\r\n\r\n/* Color overlay */\r\nbody.login main::after {\r\n  content: \"\";\r\n  position: absolute;\r\n  inset: 0;\r\n  background-color: rgba(33, 41, 49, 0.8); /* dark overlay, adjustable alpha */\r\n  mix-blend-mode: multiply; /* optional â€” helps blend with image */\r\n  z-index: -1;\r\n}\r\n\r\n.btn.dashed {\r\n    background-color:#755cef\r\n}\r\n\r\nicon-picker--choose-btn btn {\r\n    background-color:#755cef;\r\n}\r\n\r\nicon-picker--remove-btn btn {\r\n    background-color:#755cef;\r\n}\r\n\r\n.fld-new-tab-btn {\r\n    background-color:#755cef\r\n}\r\n\r\n.details>.field>.heading>label, .details>fieldset>legend {\r\n    color:white !important;\r\n}\r\n\r\n\r\n\r\n.lp-editor-container>header .btn[data-icon=xmark]:not(:hover,:active,[aria-expanded=true]), .lp-preview-container>header .btn[data-icon=xmark]:not(:hover,:active,[aria-expanded=true]) {\r\n    background-color:#755cef;\r\n}\r\n\r\nbody, html { \r\nbackground: #212931;\r\n}\r\n\r\n#alerts {\r\n    background-color:#212931 !important;\r\n    padding-top:16px;\r\n    padding-bottom:16px;\r\n}\r\n\r\n#alerts li {\r\n    box-shadow:none;\r\n}\r\n\r\n#alerts>li .btn, #alerts>li a.go {\r\n    border: 1px solid #755cef;\r\n}\r\n\r\n\r\nspan[data-icon=\"external\"][data-icon-size=\"puny\"] {\r\n  color:white;\r\n}\r\n\r\nexternal\r\n\r\n#system-info {\r\n    height:100px !important;\r\n}\r\n\r\n.btn {\r\n    color:white;\r\n}\r\n\r\n.global-sidebar__header {\r\n    height:64px;\r\n}\r\n\r\n.nav-item__subnav {\r\n    padding-bottom:16px;\r\n}\r\n\r\n:root {\r\n  --focus-ring-color: #755cef;\r\n  --primary-button-bg:#755cef;\r\n  --primary-button-bg--hover:#8e78fe;\r\n  --nav-item-bg-hover:#755cef;\r\n  --primary-button-bg--active:#8e78fe;\r\n  --text-color:#303b46;\r\n  --link-color:#755cef;\r\n  --nav-item-bg-active:#3b4956;\r\n  --error-color: #755cef;\r\n  --fg-error: #755cef;\r\n  --red-050: #1b2229;\r\n  --header-bg:#755cef;\r\n}\r\n\r\n#sidebar nav li a:not(.sel):hover {\r\n    background-color:#8e78fe;\r\n}\r\n\r\n#newgroupbtn {\r\n    background-color:#755cef;\r\n    color:white;\r\n}\r\n\r\n#groupsettingsbtn {\r\n    background-color:#755cef;\r\n    color:white;\r\n}\r\n\r\n.sidebar-action--sub .sidebar-action__prefix:before {\r\n    background-color:white;\r\n}\r\n\r\n.sidebar nav li a {\r\n    color:white;\r\n}\r\n\r\n\r\n.readable .h1, .readable h1 {\r\n    color:white;\r\n}\r\n\r\n.crumb-link {\r\n    color:white !important;\r\n}\r\n\r\nlogin-modal-intro readable {\r\n    color:white;\r\n}\r\n\r\n#crumb-list li.crumb:not(.current):after, #crumb-list li.crumb:not(.current):before {\r\n    background: #0e1215;\r\n    content: \"\";\r\n    display: block;\r\n    height: calc(var(--arrow-c)*1rem/16);\r\n    inset-inline-end: calc(var(--arrow-width)*.5rem/16);\r\n    pointer-events: none;\r\n    position: absolute;\r\n    width: 1px;\r\n}\r\n\r\ndiv.modal.login-modal.fitted {\r\n    background-color:rgba(51, 63, 77, 0.8);\r\n    color:white;\r\n}\r\n\r\nul.icons li a:hover {\r\n    background-color:#eeebfd;\r\n    border-color:transparent;\r\n}\r\n\r\n.sidebar nav li a .icon.icon-mask svg circle, .sidebar nav li a .icon.icon-mask svg ellipse, .sidebar nav li a .icon.icon-mask svg line, .sidebar nav li a .icon.icon-mask svg path, .sidebar nav li a .icon.icon-mask svg polygon, .sidebar nav li a .icon.icon-mask svg polyline, .sidebar nav li a .icon.icon-mask svg rect, .sidebar nav li a .icon.icon-mask svg text {\r\n    color:white;\r\n    background-color:white;\r\n}\r\n\r\n\r\nh1, h2, h3, h4, h5, h6,\r\np, span, strong, em, b, i,\r\nli, a, blockquote, label,\r\nth, td, caption, figcaption, small {\r\n  \r\n}\r\n\r\nbutton.fullwidth.last.submit.btn {\r\n    background-color:#755cef !important;\r\n}\r\n\r\ndiv.pane.secondary.login-form-container {\r\n    padding-left:0px;\r\n    padding-right:0px;\r\n}\r\n\r\na {\r\n    color:#755cef\r\n}\r\n\r\n.border-box.focus,\r\n.passwordwrapper.focus,\r\n.selectize.multiselect.selectize-input.focus,\r\n.text.focus {\r\n  box-shadow: 0 0 0 1px #755cef, 0 0 0 3px #755cef;\r\n}\r\n\r\na#system-info:focus, a#system-info:hover {\r\n    background-color:#755cef;\r\n}\r\n\r\n.global-sidebar__nav {\r\n    margin-top:32px;\r\n}\r\n\r\n.pane {\r\n    background-color:transparent;\r\n    color:white;\r\n    box-shadow:none;\r\n} \r\n\r\n.pane.secondary {\r\n    background-color:transparent;\r\n    box-shadow:none;\r\n}\r\n\r\n[data-sidebar=collapsed] .nav-item__trigger .menubtn {\r\n    color:white;\r\n    min-width:50px;\r\n}\r\n\r\n.btn.submit {\r\n    background-color:#755cef\r\n}\r\n\r\n.dashboard-grid.item {\r\n    background-color:none;\r\n}\r\n\r\n#global-sidebar {\r\n   \r\n   background-color: rgba(32, 39, 46, 0.90); /* 0.0 to 1.0 = transparent to solid */\r\n  background-image: url(\"https://www.transparenttextures.com/patterns/foggy-birds.png\");\r\n  background-blend-mode: multiply; /* or overlay, soft-light, etc. */\r\n}\r\n\r\n/* Header background color */\r\n#main-container #main #header {\r\n\r\n}\r\n\r\n#system-info {\r\n    display:flex;\r\n    color:white;\r\n}\r\n\r\n#system-name span {\r\n    \r\n}\r\n\r\n#nav-dashboard-link {\r\npadding-left:8px;\r\npadding-top:8px;\r\npadding-bottom:8px;\r\nmin-width:50px;\r\n}\r\n\r\n#nav-graphql-link {\r\npadding-left:8px;\r\npadding-top:8px;\r\npadding-bottom:8px;\r\nmin-width:50px;\r\n}\r\n\r\n#nav-utilities-link {\r\npadding-left:8px;\r\npadding-top:8px;\r\npadding-bottom:8px;\r\nmin-width:50px;\r\n}\r\n\r\n#nav-settings-link {\r\npadding-left:8px;\r\npadding-top:8px;\r\npadding-bottom:8px;\r\nmin-width:50px;\r\n}\r\n\r\n#nav-plugin-store-link {\r\npadding-left:8px;\r\npadding-top:8px;\r\npadding-bottom:8px;\r\nmin-width:50px;\r\n}\r\n\r\na#nav-settings-link.sidebar-action.sel::before {\r\nbackground-color:#755cef\r\n}\r\n\r\na#nav-dashboard-link.sidebar-action.sel::before {\r\nbackground-color:#755cef\r\n}\r\n\r\na#nav-graphql-link.sidebar-action.sel::before {\r\nbackground-color:#755cef\r\n}\r\n\r\na#nav-plugin-store-link.sidebar-action.sel::before {\r\nbackground-color:#755cef\r\n}\r\n\r\na#nav-utilities-link.sidebar-action.sel::before {\r\nbackground-color:#755cef\r\n}\r\n\r\n\r\n.nav-icon {\r\n    color:white;\r\n}\r\n\r\n#site-icon {\r\n  background-image: url(\"data:image/svg+xml,%3C%3Fxml version='1.0' encoding='UTF-8'%3F%3E%3Csvg id='uuid-7aadeaef-bbf6-4b99-9af4-5654b1662955' xmlns='http://www.w3.org/2000/svg' version='1.1' viewBox='0 0 226 137'%3E%3C!-- Generator: Adobe Illustrator 29.1.0, SVG Export Plug-In . SVG Version: 2.1.0 Build 142) --%3E%3Cdefs%3E%3Cstyle%3E .st0 %7B fill: %23e7e3da; %7D %3C/style%3E%3C/defs%3E%3Cg id='uuid-8ea56dec-51d4-411c-8ae9-71fd3c87655a'%3E%3Cpath class='st0' d='M221.9,10.3c1.7-2.7,3.6-7.4,4.1-10.1,0,0,0,0,0,0,0,0-.1.1-.2.2,0,0,0,0,0,0-13.9,13.6-28.1,25-42,34.6-8.9,6.1-24.5,16.2-33.3,21.1-9.4,5.3-17.2,10.6-22.5,19.5-2.1,3.5-2.3,7.3-4.2,10.8-1.5,2.7-3.6,3.9-4.8,4.9-2.2,1.9-4.8,12.5-6.1,19.2-1.2-6.7-3.9-17.3-6.1-19.2-1.1-1-3.2-2.2-4.8-4.9-1.9-3.5-2.1-7.3-4.2-10.8-5.2-8.9-13-14.2-22.5-19.5-8.7-4.9-24.4-14.9-33.3-21.1C28.3,25.3,14.2,14,.2.3c0,0,0,0,0,0,0,0-.2-.2-.2-.2C0,.2,0,.2,0,.1c.5,2.8,2.5,7.5,4.1,10.1,5.2,9,17.6,17.1,22.6,20.5-6-3.4-12-7.2-17.9-11.2.5,2.4,1.8,4.2,3.2,6.4,5.1,7.6,13.1,12.2,19.6,16.1-4.2-1.9-8.8-4.5-13-6.6,4,10.8,14.5,15.3,22.6,19-2.2-.7-8.5-3-10.6-3.9-.7-.3.8,2.2.9,2.4,5,8.5,14.7,10.9,21.9,13.7-3-.6-8.1-2.2-11.1-2.8,4.6,6.6,12.5,10.8,20.4,13.5-3-.5-8.9-2.1-8.9-2.1,2.2,2.3,5,5.2,7.7,7.2,2.2,1.6,4.6,3.2,7.1,4.5,2.4,1.2,4.9,2.3,7.5,3.1,3.4,1,6.9,1.6,10.5,1.6,1.8,0,3.5,0,5.2-.3.9-.1,1.7-.3,2.5-.4.2,0,.8-.1,1.1-.2.6.7,1.2,3.7,2,4.8,0,0,0,0,0,0-2,1.3-4.1,2.6-5.8,4-.2.2-.4.4-.5.6-1,1.7-.1,3.4,1,5.1.7-.4,1.5-.9,2.2-1.3-1.1,1.6-1.9,1.9-2.1,4.2,0,.2,0,.3,0,.5,0,0,0,.1,0,.2,0,.9.4,1.7.9,2.4.3.5.6,1,1,1.4,0,0,0,.1.1.2.3-.4,1.5-1.7,1.8-2.2,0,0,0,.2,0,.3-.5,1.4-1.4,3.7-1,5.1.4,1.2,1.1,2.4,2,3.3.5-1,1.1-2,1.6-3.1-.5,1.4-.6,3-.4,4.5.2,1.7,1.1,3.4,2.3,4.6.6-1.5,1.2-2.9,1.7-4.4-.9,3.8-.9,8.5,2.2,11.5.6-2.3,1.3-4.6,1.9-6.9-.3,3.3-.4,5.6-.4,6.7,0,.8.2,2.4,2.3,3.6,1.3.5,2.7.9,4.1,1.1,0,0,.7-7.8.7-7.8v.4c0,0,0-.1,0-.2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,.1,0,.2v-.4s.7,7.8.7,7.8c1.4-.2,2.7-.6,4.1-1.1,2.1-1.2,2.3-2.8,2.3-3.6,0-1.1-.1-3.4-.4-6.7.6,2.3,1.3,4.6,1.9,6.9,3.1-3,3.1-7.6,2.2-11.5.6,1.5,1.2,2.9,1.7,4.4,1.3-1.2,2.1-2.8,2.3-4.6.2-1.5,0-3.1-.4-4.5.5,1,1.1,2,1.6,3.1.9-.9,1.6-2.1,2-3.3.4-1.4-.5-3.7-1-5.1,0,0,0-.2,0-.3.3.4,1.5,1.7,1.8,2.2,0,0,0-.1.1-.2.4-.4.7-.9,1-1.4.5-.7.8-1.6.9-2.4,0,0,0-.1,0-.2,0-.2,0-.3,0-.5-.3-2.3-1-2.7-2.1-4.2.7.4,1.5.9,2.2,1.3,1.1-1.7,2-3.4,1-5.1-.1-.2-.3-.4-.5-.6-1.7-1.4-3.8-2.6-5.8-4,0,0,0,0,0,0,.8-1,1.5-4.1,2-4.8.2.1.8.2,1.1.2.8.2,1.7.3,2.5.4,1.7.2,3.5.3,5.2.3,3.5,0,7.1-.6,10.5-1.6,2.6-.8,5.2-1.9,7.5-3.1,2.5-1.3,4.9-2.8,7.1-4.5,2.7-2,5.5-4.8,7.7-7.2,0,0-5.9,1.6-8.9,2.1,7.9-2.7,15.8-6.9,20.4-13.5-3,.7-8.1,2.3-11.1,2.8,7.2-2.8,16.9-5.2,21.9-13.7.1-.2,1.6-2.7.9-2.4-2.2.9-8.5,3.2-10.6,3.9,8.1-3.7,18.6-8.2,22.6-19-4.2,2.1-8.8,4.7-13,6.6,6.5-3.9,14.5-8.6,19.6-16.1,1.4-2.2,2.7-4,3.2-6.4-5.9,4.1-11.9,7.8-17.9,11.2,5-3.4,17.5-11.5,22.6-20.5h0Z'/%3E%3C/g%3E%3C/svg%3E\");\r\nbackground-repeat: no-repeat no-repeat;\r\nbackground-position: center center;\r\nbackground-size: cover;\r\nheight:21px;\r\nwidth:32px;\r\n}\r\n\r\n#site-icon svg {\r\n    \r\n}\r\n\r\n#site-icon svg {\r\n    visibility: hidden;\r\n    \r\n}\r\n\r\n/* H1 tags */\r\nh1 {\r\n    color: #ffffff;\r\n}\r\n\r\n.label {\r\n    color:white;\r\n}\r\n\r\n\r\n\r\n/* Standard button color */\r\n.btn.submit {\r\n    background: #da5a47;\r\n}\r\n/* Hover button color */\r\n.btn.submit:not(.disabled):not(.inactive):hover,\r\n.btn.submit:not(.disabled):not(.inactive).hover {\r\n    background: #bf503f;\r\n}\r\n/* Active button color */\r\n.btn.submit:not(.disabled):not(.inactive):active,\r\n.btn.submit:not(.disabled):not(.inactive).active {\r\n    background: #8c3b2e;\r\n}\r\n\r\nbody.fixed-header #header {\r\n    -webkit-backdrop-filter: none;\r\n    backdrop-filter: none;\r\n    background-color:#212931;\r\n    padding-top:16px;\r\n    padding-bottom:16px;\r\n}\r\n\r\n.widget.craft\\\\widgets\\\\craftsupport .front .pane .cs-screen-home .cs-opt:hover {\r\n    background-color:#2f3944;\r\n}\r\n\r\n.sidebar nav li:not(.has-subnav) [data-source-item].active-drop-target, .sidebar nav li:not(.has-subnav) [data-source-item].sel, .sidebar nav li:not(.has-subnav)>a.active-drop-target, .sidebar nav li:not(.has-subnav)>a.sel {\r\n    background-color:#755cef;\r\n}"
      cacheBusting: true
      cssFile: ''
  cp-nav:
    edition: standard
    enabled: true
    schemaVersion: 2.0.11
  dashboard-begone:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  servd-asset-storage:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
    settings:
      adjustFeedmeLogs: ''
      assetsEnvironment: ''
      assetsEnvironmentOverwrite: ''
      cacheClearMode: full
      clearCachesOnSave: always
      clearCdnCacheWhenAssetChanges: '1'
      disableDynamic: ''
      disableTransforms: ''
      fsMaps:
        __assoc__:
          -
            - pouredOutAssets
            - none
      fsMapsEnabled: ''
      imageAutoConversion: webp
      injectCors: ''
      projectSlug: keen-barbet
      securityKey: EuOQgdNu53BVqShYJ7Esq5rpDR13Ajes
      suppressWarnings: '1'
      transformSvgs: 'no'
      useLocalVolumes: false
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: Filament
  retryDuration: null
  schemaVersion: 5.8.0.3
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
