fieldLayouts:
  906d9e75-c2b1-46b7-9390-41a4084aa7aa:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-12-30T01:23:21+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 144593fe-da30-41d5-8ec8-b757273bb41b # Announcement
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7579b6a9-6b11-409f-95ab-826efcec47bc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-10T18:30:19+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ffa62b38-7996-4d0e-9542-8dfcce600f43 # About
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c28748db-8b40-481d-ad86-5a5924931a5a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-10T18:30:19+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4b62f1ab-cb3e-490e-ad54-2a72dc774c37 # Blogs
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9de2eed9-e3e6-4b31-865f-7e6d5aa6124f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-10T18:30:19+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: affe6a11-2e34-40ec-a742-3766960fdfd3 # Gallery
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 470ea3ad-486b-4eeb-8804-819c30e814ff
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-10T18:30:54+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 768f6b29-6796-4341-baed-ce919fde46a6 # Shop
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 47f77d4e-189a-4d0b-9fa3-25dbf82550a8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 12f3f275-f50a-4824-b1a0-e5bea658a954
        userCondition: null
handle: globalContent
name: 'Global Content'
sortOrder: 1
