fieldLayouts:
  906d9e75-c2b1-46b7-9390-41a4084aa7aa:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-12-30T01:23:21+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 144593fe-da30-41d5-8ec8-b757273bb41b # Announcement
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7579b6a9-6b11-409f-95ab-826efcec47bc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 12f3f275-f50a-4824-b1a0-e5bea658a954
        userCondition: null
handle: globalContent
name: 'Global Content'
sortOrder: 1
