currLabel: Globals
customIcon: null
enabled: true
handle: globals
icon: globe
layout: 161e35c5-199b-4d9c-b090-9dc1c61bc616 # Default
level: 1
newWindow: false
parent: null
prevLabel: Globals
prevLevel: 1
prevParent: null
prevUrl: globals
sortOrder: 13
type: craft
url: globals
